### ISSUE TITLE
[控制台]视频标题输入字符时超出长度未自动换行

### ISSUE THREAD

**Issue by shixiaoyanjj** [Venvy-dev/demand#923]
问题描述：
>视频标题输入字符时超出长度未自动换行

![image](https://cloud.githubusercontent.com/assets/16204026/15852628/59f8fc2c-2cd4-11e6-830e-42c2ea398449.png)

期望结果：
>制定统一的换行规则，让页面显示优美

请@summernini 指派开发人员完成

**Comment by nekronhuang** [comment]
给td标签加一个css属性，就可以了，因为不间断的英文/数字被html认为是一个单词，所以无法拆分了
```css
td {
  word-break: break-all;
}
```
